### ISSUE TITLE
Connect Timeout Error

### ISSUE THREAD

**Issue by KvN069** [Upikk/Fiveguard_Discordbot#2]
```lua
[script:Fiveguard_Discordbot] ConnectTimeoutError: Connect Timeout Error
[script:Fiveguard_Discordbot]     at onConnectTimeout (C:\FiveM\txData\Server\resources\[fiveguard]\Fiveguard_Discordbot\node_modules\undici\lib\core\connect.js:182:24)
[script:Fiveguard_Discordbot]     at C:\FiveM\txData\Server\resources\[fiveguard]\Fiveguard_Discordbot\node_modules\undici\lib\core\connect.js:129:46
[script:Fiveguard_Discordbot]     at C:\FiveM\txData\Server\resources\[fiveguard]\Fiveguard_Discordbot\node_modules\undici\lib\core\connect.js:168:33
[script:Fiveguard_Discordbot]     at Object.callback (citizen:/scripting/v8/timer.js:145:21)
[script:Fiveguard_Discordbot]     at onTick (citizen:/scripting/v8/timer.js:171:27)
[script:Fiveguard_Discordbot]     at citizen:/scripting/v8/timer.js:270:13
[script:Fiveguard_Discordbot]     at Number.__cfx_wrap_318 (citizen:/scripting/v8/main.js:23:12)
[script:Fiveguard_Discordbot]     at citizen:/scripting/v8/main.js:29:16
[script:Fiveguard_Discordbot]     at citizen:/scripting/v8/timer.js:269:16
```

**Comment by KvN069** [comment]
@Upikk any fix for that?
